<?xml version="1.0" encoding="UTF-8"?><testrun name="LogRollbackTest" project="mysimpledb" tests="6" started="6" failures="1" errors="0" ignored="0">
  <testsuite name="simpledb.systemtest.LogRollbackTest" time="1.29">
    <testcase name="TestRollback" classname="simpledb.systemtest.LogRollbackTest" time="0.116"/>
    <testcase name="TestNoRollback" classname="simpledb.systemtest.LogRollbackTest" time="0.137">
      <failure>junit.framework.AssertionFailedError: Error!  Should not be able to able to abort a committed transaction!
	at junit.framework.Assert.fail(Assert.java:47)
	at simpledb.systemtest.LogRollbackTest.TestNoRollback(LogRollbackTest.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:73)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:46)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:180)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:41)
	at org.junit.runners.ParentRunner$1.evaluate(ParentRunner.java:173)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:220)
	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:39)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:79)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
    </testcase>
    <testcase name="TestRollbackWithOthers" classname="simpledb.systemtest.LogRollbackTest" time="0.256"/>
    <testcase name="TestRollbackWithCheckPoint" classname="simpledb.systemtest.LogRollbackTest" time="0.301"/>
    <testcase name="TestAbortCommitInterleaved" classname="simpledb.systemtest.LogRollbackTest" time="0.446"/>
    <testcase name="TestFlushAll" classname="simpledb.systemtest.LogRollbackTest" time="0.034"/>
  </testsuite>
</testrun>
